name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os:
          - name: ubuntu-latest
          - name: macos-latest
          - name: windows-latest
    runs-on: ${{ matrix.os.name }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17.8"

      - name: Install V
        uses: vlang/setup-v@v1

      - name: Get go2v
        uses: actions/checkout@v2

      - name: Check GO env variables
        run: go env && v -e 'import os; os.getenv("PATH").split(os.path_delimiter).map(dump(it))'

      - name: Check code formatting
        run: |
          v fmt -diff .
          v fmt -verify .

      - name: Build go2v
        run: v .

      - name: Run tests
        run: v -g test .

      - name: Run complex tests
        run: |
          v -o go2v .
          ./go2v complex_tests/esbuild/api_impl/api_impl.go
          ./go2v complex_tests/esbuild/resolver/resolver.go
          ./go2v complex_tests/esbuild/linker/linker.go
          ./go2v complex_tests/esbuild/bundler/bundler.go
          ./go2v complex_tests/esbuild/css_parser/css_parser.go
